---
interfaces:
  - name: e1/16
    description: CLR-4045
    vlan:
      - 976  
      - 977  
      - 3730 
      - 3731 
      - 3732 
      - 3733 
      - 3734 
      - 3735 
      - 3736 
      - 3737 
      - 3738 
      - 3739 
      - 3740 
      - 3741 
      - 3742 
      - 3743 
      - 3744 
      - 3745 
      - 3746 
      - 3747 
      - 3748 
  - name: e/17
    description: CLR-1234
    vlan:
      - 400
      - 401
      - 402
      - 403
      - 404
      - 405
